import { redirect } from "next/navigation";
import Link from "next/link";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import "./assistant.css";

type Lead = { id: string; organisation_id: string; service_interest: string | null; problem_summary: string | null; preferred_contact_channel: string | null; status: string; created_at: string };
type Organisation = { id: string; name: string };
type Conversation = { id: string; lead_id: string; channel: string; status: string; ai_enabled: boolean; last_message_at: string | null; created_at: string };
type Handoff = { id: string; lead_id: string; reason: string; priority: string; status: string; requested_at: string };
const channelLabel: Record<string,string>={website_chat:"Website chat",whatsapp:"WhatsApp",voice_call:"Voice call",email:"Email"};
const statusLabel: Record<string,string>={active:"AI active",waiting_client:"Waiting for client",waiting_ai:"Waiting for AI",human_required:"Needs human",human_active:"Human active",completed:"Completed",paused:"Paused"};

export default async function AssistantPage(){
 const supabase=await createSupabaseServerClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect("/login");
 const {data:role}=await supabase.rpc("get_my_role" as never); if(!["admin","operator","reviewer"].includes(String(role??""))) redirect("/");
 const db=supabase as any;
 const [{data:leadRows,error:leadError},{data:orgRows,error:orgError},{data:conversationRows,error:conversationError},{data:handoffRows,error:handoffError}]=await Promise.all([
  db.from("leads").select("id,organisation_id,service_interest,problem_summary,preferred_contact_channel,status,created_at").order("created_at",{ascending:false}).limit(30),
  db.from("organisations").select("id,name").limit(200),
  db.from("assistant_conversations").select("id,lead_id,channel,status,ai_enabled,last_message_at,created_at").order("last_message_at",{ascending:false,nullsFirst:false}).limit(50),
  db.from("assistant_handoffs").select("id,lead_id,reason,priority,status,requested_at").eq("status","open").order("requested_at",{ascending:false}).limit(20)
 ]);
 if(leadError) throw new Error(leadError.message); if(orgError) throw new Error(orgError.message); if(conversationError) throw new Error(conversationError.message); if(handoffError) throw new Error(handoffError.message);
 const leads=(leadRows??[]) as Lead[], orgs=(orgRows??[]) as Organisation[], conversations=(conversationRows??[]) as Conversation[], handoffs=(handoffRows??[]) as Handoff[];
 const orgById=new Map(orgs.map(o=>[o.id,o.name])); const active=conversations.filter(c=>["active","waiting_client","waiting_ai"].includes(c.status)); const waiting=conversations.filter(c=>c.status==="waiting_client"); const ready=leads.filter(l=>l.status==="new"&&!conversations.some(c=>c.lead_id===l.id));
 return <main className="page-shell assistant-page">
  <header className="page-header assistant-header"><div><div className="eyebrow">AI Operations</div><h1>Assistant</h1><p>The operating workspace for AI-led client conversations, workflow progress, actions and human handoff.</p></div><div className="assistant-header-actions"><Link className="ghost-button" href="/leads">View leads</Link><Link className="primary-button" href="/settings/integrations/ai">AI settings →</Link></div></header>
  <section className="assistant-hero"><div><span className="assistant-live"><i/> Assistant workspace</span><h2>Turn every enquiry into a guided conversation.</h2><p>Leads remain the source of truth. The Assistant adds a persistent conversation layer, business workflows, structured requirements and controlled actions around each lead.</p></div><div className="assistant-hero-state"><span>Operating mode</span><strong>Human governed</strong><small>AI can propose and prepare actions. Consequential external actions remain controlled.</small></div></section>
  <section className="lead-summary assistant-metrics"><div className="summary-card"><span>Active conversations</span><strong>{active.length}</strong></div><div className="summary-card"><span>Waiting for client</span><strong>{waiting.length}</strong></div><div className="summary-card"><span>New leads ready</span><strong>{ready.length}</strong></div><div className="summary-card"><span>Human attention</span><strong>{handoffs.length}</strong></div></section>
  <section className="assistant-grid"><div className="assistant-main-column">
   <section className="table-card"><div className="section-heading"><div><div className="eyebrow">Client inbox</div><h2>Conversations</h2><p>Every channel will converge into the same operational conversation model.</p></div><span className="badge">{conversations.length} conversations</span></div>
    {conversations.length===0?<div className="assistant-empty"><div className="assistant-empty-icon">✦</div><strong>No AI conversations yet</strong><span>New website enquiries are already arriving in Leads. The next automation layer will create the persistent conversation here.</span><Link className="primary-button" href="/leads">Open leads →</Link></div>:<div className="assistant-conversation-list">{conversations.map(c=>{const lead=leads.find(l=>l.id===c.lead_id);const org=lead?orgById.get(lead.organisation_id):"Unknown organisation";return <Link href={`/assistant/conversations/${c.id}`} className="assistant-conversation" key={c.id}><div className="assistant-avatar">{(org??"?").slice(0,1).toUpperCase()}</div><div className="assistant-conversation-main"><div className="assistant-conversation-top"><strong>{org}</strong><span>{channelLabel[c.channel]??c.channel}</span></div><p>{lead?.service_interest??"Service not set"}</p><small>{lead?.problem_summary??"No conversation summary yet."}</small></div><div className="assistant-conversation-status"><span className={`assistant-status-dot ${c.status==="human_required"?"warn":""}`}/><span>{statusLabel[c.status]??c.status}</span>{c.last_message_at&&<time>{new Date(c.last_message_at).toLocaleString()}</time>}</div></Link>})}</div>}
   </section>
   <section className="table-card"><div className="section-heading"><div><div className="eyebrow">Ready queue</div><h2>New leads awaiting Assistant</h2><p>These leads have arrived but do not yet have a conversation.</p></div></div>{ready.length===0?<div className="assistant-inline-empty">No unassigned new leads in the current queue.</div>:<div className="assistant-lead-list">{ready.slice(0,8).map(l=><Link className="assistant-lead-row" href={`/leads/${l.id}`} key={l.id}><div><strong>{orgById.get(l.organisation_id)??"Unknown organisation"}</strong><span>{l.service_interest??"Service not set"}</span></div><div><span className="assistant-channel">{channelLabel[l.preferred_contact_channel??""]??"Channel not selected"}</span><small>{new Date(l.created_at).toLocaleString()}</small></div><span className="text-link">Open lead →</span></Link>)}</div>}</section>
  </div><aside className="assistant-side-column">
   <section className="table-card"><div className="section-heading"><div><div className="eyebrow">Attention</div><h2>Human handoffs</h2></div></div>{handoffs.length===0?<div className="assistant-side-empty"><strong>No open handoffs</strong><span>The Assistant has not requested human attention yet.</span></div>:<div className="assistant-handoff-list">{handoffs.map(h=><div className="assistant-handoff" key={h.id}><div className="assistant-handoff-top"><strong>{orgById.get(leads.find(l=>l.id===h.lead_id)?.organisation_id??"")??"Lead"}</strong><span>{h.priority}</span></div><p>{h.reason}</p><small>{new Date(h.requested_at).toLocaleString()}</small></div>)}</div>}</section>
   <section className="table-card"><div className="section-heading"><div><div className="eyebrow">Assistant model</div><h2>How it works</h2></div></div><ol className="assistant-flow"><li><b>1</b><div><strong>Lead enters</strong><span>Website enquiry and preferred channel are stored in Operations.</span></div></li><li><b>2</b><div><strong>Conversation starts</strong><span>The selected channel creates one persistent conversation.</span></div></li><li><b>3</b><div><strong>Workflow advances</strong><span>The Assistant asks for information required by the service workflow.</span></div></li><li><b>4</b><div><strong>Action or handoff</strong><span>Tools update records, create follow-ups or request a human.</span></div></li></ol></section>
  </aside></section>
 </main>;
}
