import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { Database } from "@/lib/data/supabase/database.types";

type Organisation = Database["public"]["Tables"]["organisations"]["Row"];
type Lead = Database["public"]["Tables"]["leads"]["Row"];
type Prospect = Database["public"]["Tables"]["prospects"]["Row"];
type Opportunity = Database["public"]["Tables"]["opportunities"]["Row"];
type AuditEvent = Database["public"]["Tables"]["audit_events"]["Row"];
type UserRole = "admin" | "operator" | "reviewer";

const statusLabels: Record<string, string> = { new:"New", researching:"Researching", qualified:"Qualified", outreach_ready:"Outreach ready", contacted:"Contacted", engaged:"Engaged", opportunity:"Opportunity", won:"Won", lost:"Lost", nurture:"Nurture" };
const funnelStages = [{ key:"new", label:"New", color:"neutral" }, { key:"qualified", label:"Qualified", color:"blue" }, { key:"outreach_ready", label:"Outreach", color:"violet" }, { key:"engaged", label:"Engaged", color:"amber" }, { key:"opportunity", label:"Opportunity", color:"green" }, { key:"won", label:"Won", color:"green" }];

export default async function Dashboard() {
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");
  const { data: roleValue, error: roleError } = await supabase.rpc("get_my_role" as never);
  const userRole = roleError ? undefined : (roleValue as UserRole | null | undefined);
  if (!userRole || !["admin", "operator", "reviewer"].includes(userRole)) return <main className="auth-shell"><section className="auth-card"><div className="eyebrow">ABE TechLab Operations</div><h1>Access pending</h1><p>Your account is authenticated, but it has not been assigned an Operations role yet.</p><small>Ask an administrator to assign you as an administrator, operator, or reviewer.</small></section></main>;

  const [leadsResult, organisationsResult, prospectsResult, activitiesResult, opportunitiesResult, strategiesResult, campaignsResult] = await Promise.all([
    supabase.from("leads").select("id, organisation_id, service_interest, status, score, problem_summary, created_at").order("created_at", { ascending:false }).limit(100),
    supabase.from("organisations").select("id, name, industry, geography, website_url").order("created_at", { ascending:false }).limit(100),
    supabase.from("prospects").select("id, organisation_id, status, score, confidence, recommended_service, likely_need").order("created_at", { ascending:false }).limit(50),
    supabase.from("audit_events").select("id, actor_type, action, entity_type, entity_id, metadata, created_at").order("created_at", { ascending:false }).limit(8),
    supabase.from("opportunities").select("id, organisation_id, name, stage, value, probability, updated_at").order("updated_at", { ascending:false }).limit(100),
    supabase.from("outreach_strategies").select("id, objective, service, channel, status, created_at").in("status", ["needs_review", "draft"]).order("created_at", { ascending:false }).limit(100),
    supabase.from("campaigns").select("id, strategy_id, status, channel, created_at").in("status", ["draft"]).order("created_at", { ascending:false }).limit(100),
  ]);
  for (const result of [leadsResult, organisationsResult, prospectsResult, activitiesResult, opportunitiesResult, strategiesResult, campaignsResult]) if (result.error) throw new Error(result.error.message);

  const leads = (leadsResult.data ?? []) as Pick<Lead,"id"|"organisation_id"|"service_interest"|"status"|"score"|"problem_summary"|"created_at">[];
  const organisations = (organisationsResult.data ?? []) as Pick<Organisation,"id"|"name"|"industry"|"geography"|"website_url">[];
  const prospects = (prospectsResult.data ?? []) as Pick<Prospect,"id"|"organisation_id"|"status"|"score"|"confidence"|"recommended_service"|"likely_need">[];
  const activities = (activitiesResult.data ?? []) as Pick<AuditEvent,"id"|"actor_type"|"action"|"entity_type"|"entity_id"|"metadata"|"created_at">[];
  const opportunities = (opportunitiesResult.data ?? []) as Pick<Opportunity,"id"|"organisation_id"|"name"|"stage"|"value"|"probability"|"updated_at">[];
  const strategyQueue = (strategiesResult.data ?? []) as Pick<Database["public"]["Tables"]["outreach_strategies"]["Row"],"id"|"objective"|"service"|"channel"|"status"|"created_at">[];
  const campaignQueue = (campaignsResult.data ?? []) as Pick<Database["public"]["Tables"]["campaigns"]["Row"],"id"|"strategy_id"|"status"|"channel"|"created_at">[];

  const organisationById = new Map(organisations.map((organisation) => [organisation.id, organisation]));
  const highPriority = leads.filter((lead) => (lead.score ?? 0) >= 85);
  const openOpportunities = opportunities.filter((opportunity) => !["won", "lost"].includes(opportunity.stage));
  const pendingApprovals = strategyQueue.filter((item) => item.status === "needs_review").length + campaignQueue.length;
  const outreachDrafts = strategyQueue.filter((item) => item.status === "needs_review").length + campaignQueue.length;
  const engagedLeads = leads.filter((lead) => ["engaged", "opportunity", "won"].includes(lead.status)).length;
  const conversionRate = leads.length ? Math.round((engagedLeads / leads.length) * 100) : 0;
  const funnelCounts = funnelStages.map((stage) => leads.filter((lead) => lead.status === stage.key).length);
  const topProspects = [...prospects].sort((a,b)=>(b.score??0)-(a.score??0)).slice(0,4);
  const quickActions = [{ href:"/approval", label:"Review approvals", note:`${pendingApprovals} pending decision${pendingApprovals === 1 ? "" : "s"}` }, { href:"/opportunities", label:"Open pipeline", note:`${openOpportunities.length} open opportunit${openOpportunities.length === 1 ? "y" : "ies"}` }, { href:"/leads", label:"Review leads", note:`${highPriority.length} high-priority lead${highPriority.length === 1 ? "" : "s"}` }, { href:"/outreach", label:"Prepare outreach", note:`${outreachDrafts} item${outreachDrafts === 1 ? "" : "s"} awaiting review` }];

  return <main className="main dashboard-main">
    <header className="header dashboard-header"><div><div className="eyebrow">Internal operations · {userRole}</div><h1>Good morning.</h1><p className="header-subtitle">Here is what needs attention across the revenue engine.</p></div><div className="header-actions"><span className="connection"><span className="dot" /> Supabase connected</span><a className="ghost-button" href="/ai">AI Control Centre</a></div></header>
    <section className="command-bar" aria-label="Quick actions"><div><strong>What needs attention?</strong><span>Jump directly into the highest-value operational work.</span></div><div className="quick-actions">{quickActions.map((action)=><a className="quick-action" href={action.href} key={action.href}><span>{action.label}</span><small>{action.note}</small><b>→</b></a>)}</div></section>
    <section className="metrics"><a className="metric-card featured metric-card-link" href="/leads"><div className="metric-label">Pipeline leads</div><div className="metric-value">{leads.length}</div><div className="metric-foot"><span>Current pipeline</span><span className="trend">{conversionRate}% engaged</span></div></a><a className="metric-card metric-card-link" href="/leads"><div className="metric-label">High priority</div><div className="metric-value">{highPriority.length}</div><div className="metric-foot"><span>Fit score 85+</span><span>Review →</span></div></a><a className="metric-card metric-card-link" href="/opportunities"><div className="metric-label">Open opportunities</div><div className="metric-value">{openOpportunities.length}</div><div className="metric-foot"><span>Active pipeline</span><span>Open →</span></div></a><a className="metric-card metric-card-link" href="/approval"><div className="metric-label">Pending approvals</div><div className="metric-value">{pendingApprovals}</div><div className="metric-foot"><span>Human decisions</span><span>Review →</span></div></a></section>
    <section className="dashboard-grid top-grid"><div className="card pipeline-card"><div className="section-heading"><div><div className="eyebrow">Revenue engine</div><h2>Pipeline health</h2><p>Where leads are moving and where attention is needed.</p></div><a className="text-link" href="/leads">View leads →</a></div><div className="funnel">{funnelStages.map((stage,i)=>{const count=funnelCounts[i],max=Math.max(...funnelCounts,1);return <div className="funnel-row" key={stage.key}><span className={`funnel-dot ${stage.color}`} /><strong>{stage.label}</strong><div className="funnel-track"><span style={{width:`${Math.max(count?(count/max)*100:3,3)}%`}} /></div><b>{count}</b></div>})}</div></div><div className="card aria-card"><div className="aria-top"><div><div className="eyebrow">AI intelligence layer</div><h2>ARIA</h2></div><span className="mode-pill">Advisory mode</span></div><div className="aria-brief"><span className="aria-icon">✦</span><div><strong>AI execution is paused</strong><p>The Operations platform remains usable. Human workflows continue without provider access.</p></div></div><div className="aria-stats"><div><b>{prospects.length}</b><span>Prospects</span></div><div><b>{highPriority.length}</b><span>High-fit leads</span></div><div><b>{pendingApprovals}</b><span>Approvals</span></div></div><a className="aria-action" href="/ai">Open AI Control Centre <span>→</span></a></div></section>
    <section className="dashboard-grid bottom-grid"><div className="card"><div className="section-heading"><div><div className="eyebrow">Governance</div><h2>Approval queue</h2><p>Human review before strategies and campaigns become operational.</p></div><a className="text-link" href="/approval">Open queue →</a></div><div className="compact-list">{strategyQueue.slice(0,3).map((item)=><a className="compact-row" href="/approval" key={item.id}><div><strong>{item.objective}</strong><span>{item.channel} · {item.service ?? "Service not set"}</span></div><span className="status-chip">Needs review</span></a>)}{campaignQueue.slice(0,2).map((item)=><a className="compact-row" href="/approval" key={item.id}><div><strong>Campaign draft</strong><span>{item.channel} · {new Date(item.created_at).toLocaleDateString()}</span></div><span className="status-chip">Pending</span></a>)}{pendingApprovals === 0 && <div className="empty-stage"><strong>Nothing pending</strong><span>The approval queue is clear.</span></div>}</div></div><div className="card"><div className="section-heading"><div><div className="eyebrow">Outreach</div><h2>Drafts awaiting approval</h2><p>Prepared outbound work that still needs a human decision.</p></div><a className="text-link" href="/outreach">Open outreach →</a></div><div className="compact-list">{outreachDrafts === 0 ? <div className="empty-stage"><strong>No drafts awaiting approval</strong><span>Create a strategy or campaign from Outreach.</span><a href="/outreach">Prepare outreach →</a></div> : <><a className="compact-row" href="/approval"><div><strong>{strategyQueue.filter((item)=>item.status === "needs_review").length} strategies</strong><span>Human review required</span></div><span className="status-chip">Review</span></a><a className="compact-row" href="/approval"><div><strong>{campaignQueue.length} campaigns</strong><span>Draft campaigns</span></div><span className="status-chip">Draft</span></a></>}</div></div></section>
    <section className="dashboard-grid activity-grid"><div className="card"><div className="section-heading"><div><div className="eyebrow">Pipeline</div><h2>Open opportunities</h2><p>Current commercial work that is still active.</p></div><a className="text-link" href="/opportunities">View pipeline →</a></div><div className="compact-list">{openOpportunities.length === 0 ? <div className="empty-stage"><strong>No open opportunities</strong><span>Create one from the Opportunities workspace.</span><a href="/opportunities">Open opportunities →</a></div> : openOpportunities.slice(0,5).map((opportunity)=><a className="compact-row" href="/opportunities" key={opportunity.id}><div><strong>{opportunity.name}</strong><span>{organisationById.get(opportunity.organisation_id)?.name ?? "Unknown organisation"} · {opportunity.stage}</span></div><span className="status-chip">{opportunity.probability ?? 0}%</span></a>)}</div></div><div className="card"><div className="section-heading"><div><div className="eyebrow">Control</div><h2>Recent activity</h2><p>Auditable actions across the Operations system.</p></div><span className="badge">{activities.length} recent</span></div><div className="compact-list">{activities.length === 0 ? <div className="empty-stage"><span>No audit activity yet.</span></div> : activities.map((activity)=><div className="compact-row" key={activity.id}><div><strong>{activity.action}</strong><span>{activity.actor_type} · {activity.entity_type} · {new Date(activity.created_at).toLocaleString()}</span></div><span className="status-chip">Recorded</span></div>)}</div></div></section>
    <section className="card" style={{marginTop:14}}><div className="section-heading"><div><div className="eyebrow">Research queue</div><h2>Top prospects</h2><p>Research-backed records already available to the Operations system.</p></div><a className="text-link" href="/prospecting">Open research →</a></div><div className="prospect-list">{topProspects.length === 0 ? <div className="empty-stage"><strong>No prospects yet</strong><span>Research can be queued while AI execution is paused.</span></div> : topProspects.map((prospect)=><a className="prospect-row" href="/prospecting" key={prospect.id}><div className="prospect-avatar">{(organisationById.get(prospect.organisation_id)?.name ?? "?").slice(0,1).toUpperCase()}</div><div><strong>{organisationById.get(prospect.organisation_id)?.name ?? "Unknown organisation"}</strong><span>{prospect.recommended_service ?? "Service opportunity"}</span></div><b>{prospect.score ?? "—"}</b></a>)}</div></section>
  </main>;
}
